{% set name = "aiobotocore" %}
{% set version = "2.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03d64a41e313ebce76fd7c3e4c854e560032ac5cf71f4d5072616ca6fb9701b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=72.2.0
  run:
    - python >={{ python_min }}
    - aiohttp >=3.9.2,<4.0.0
    - aioitertools >=0.5.1,<1.0.0
    - botocore >=1.37.0,<1.37.2
    - python-dateutil >=2.1,<3.0.0
    - jmespath >=0.7.1,<2.0.0
    - multidict >=6.0.0,<7.0.0
    # c/f noarch means no selectors, so the least restrictive
    # urllib3 dep is specified here
    - urllib3 >=1.25.4,!=2.2.0,<3
    - wrapt >=1.10.10,<2.0.0

test:
  imports:
    - aiobotocore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aio-libs/aiobotocore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Async client for aws services using botocore and aiohttp
  description: |
    Main purpose of this library to support amazon s3 api, but other services
    should work (may be with minor fixes). For now it has been tested only for
    upload/download api for s3. It has been reported that SQS and Dynamo
    services also work.
  doc_url: http://aiobotocore.readthedocs.io
  dev_url: https://github.com/aio-libs/aiobotocore

extra:
  recipe-maintainers:
    - nehaljwani
    - fhoehle
